"""
Script pour peupler la base de données avec un inventaire de démo ULTRA RÉALISTE
INVENTAIRE COMPLET DE GARAGE AUTOMOBILE avec vraies références, vraies photos et vrais paramètres
"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv
from pathlib import Path
import random
import string
from datetime import datetime, timezone, timedelta

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

# MongoDB connection
mongo_url = os.environ.get('MONGO_URL')
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ.get('DB_NAME', 'bms_inventory')]

def generate_sku():
    return 'BMS-' + ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))

# 🖼️ URLs d'images par catégorie (images gratuites Unsplash)
IMAGES_BY_CATEGORY = {
    'alternateur': ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&q=80'],
    'demarreur': ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&q=80'],
    'batterie': ['https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80'],
    'capteur': ['https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80'],
    'bobine': ['https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80'],
    'plaquettes': ['https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=800&q=80'],
    'disques': ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&q=80'],
    'etrier': ['https://images.unsplash.com/photo-1614368148747-ec6efe52f878?w=800&q=80'],
    'filtre': ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&q=80'],
    'radiateur': ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&q=80'],
    'pompe': ['https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80'],
    'embrayage': ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&q=80'],
    'courroie': ['https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80'],
    'amortisseur': ['https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&q=80'],
    'rotule': ['https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80'],
    'cremaillere': ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&q=80'],
    'phare': ['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80'],
    'retroviseur': ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80'],
    'pare_choc': ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80'],
    'huile': ['https://images.unsplash.com/photo-1554672723-d42a16e533db?w=800&q=80'],
    'liquide_refroidissement': ['https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80'],
    'liquide_frein': ['https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=800&q=80'],
    'lave_glace': ['https://images.unsplash.com/photo-1554672723-d42a16e533db?w=800&q=80'],
    'graisse': ['https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80'],
    'default': ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&q=80']
}

def get_image_for_article(nom):
    """Retourne une image appropriée selon le nom de l'article"""
    nom_lower = nom.lower()
    
    for key in IMAGES_BY_CATEGORY:
        if key.replace('_', ' ') in nom_lower:
            return IMAGES_BY_CATEGORY[key]
    
    return IMAGES_BY_CATEGORY['default']

# 🚗 INVENTAIRE COMPLET DE GARAGE - PIÈCES DÉTACHÉES 🚗
PIECES_DATA = [
    # === ÉLECTRICITÉ ===
    {
        'nom': 'Alternateur Bosch 14V 90A',
        'ref': '0124525015',
        'description': 'Alternateur 14V 90A pour véhicules essence et diesel. Compatible Renault Clio, Megane, Peugeot 206, 307, Citroën C3, C4. Qualité OE, garantie 2 ans. Tension de sortie stable, régulateur intégré.',
        'etat': 'Comme neuf',
        'categorie': 'Électricité',
        'sous_categorie': 'Alternateur, Bosch',
        'prix_neuf': 285.00,
        'prix_achat': 120.00,
        'prix_vente': 199.00,
        'quantite': 3,
        'public': True,
        'lieu': 'Étagère A-3',
    },
    {
        'nom': 'Démarreur Valeo 12V 1.1kW',
        'ref': 'D6RA133',
        'description': 'Démarreur 12V 1.1kW pour véhicules diesel. Compatible Renault Clio 3, Megane 2, Modus 1.5 dCi. Rotation horaire, 9 dents. Garantie 18 mois.',
        'etat': 'Très bon état',
        'categorie': 'Électricité',
        'sous_categorie': 'Démarreur, Valeo',
        'prix_neuf': 320.00,
        'prix_achat': 95.00,
        'prix_vente': 165.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Étagère A-4',
    },
    {
        'nom': 'Batterie Varta Blue Dynamic E11',
        'ref': 'E11 574012068',
        'description': 'Batterie 12V 74Ah 680A (EN). Démarrage à froid garanti jusqu\'à -18°C. Technologie calcium-argent, maintenance facile, faible autodécharge. Dimensions: 278x175x190mm.',
        'etat': 'Comme neuf',
        'categorie': 'Électricité',
        'sous_categorie': 'Batterie, Varta',
        'prix_neuf': 125.00,
        'prix_achat': 75.00,
        'prix_vente': 98.00,
        'quantite': 5,
        'public': True,
        'lieu': 'Zone batterie',
    },
    {
        'nom': 'Capteur ABS Bosch Avant',
        'ref': '0265006800',
        'description': 'Capteur de vitesse roue ABS avant gauche/droit. Compatible Peugeot 307, 308, Citroën C4, C5. Précision maximale, détection magnétique. Installation plug & play.',
        'etat': 'Comme neuf',
        'categorie': 'Électricité',
        'sous_categorie': 'Capteur ABS, Bosch',
        'prix_neuf': 68.00,
        'prix_achat': 32.00,
        'prix_vente': 48.00,
        'quantite': 4,
        'public': True,
        'lieu': 'Étagère B-2',
    },
    {
        'nom': 'Bobine d\'allumage Beru',
        'ref': 'ZSE001',
        'description': 'Bobine d\'allumage haute performance. Compatible Renault 1.4 16V, 1.6 16V essence. Résistance optimale, étanchéité IP54. Améliore le démarrage à froid.',
        'etat': 'Comme neuf',
        'categorie': 'Électricité',
        'sous_categorie': 'Allumage, Beru',
        'prix_neuf': 45.00,
        'prix_achat': 22.00,
        'prix_vente': 34.00,
        'quantite': 6,
        'public': True,
        'lieu': 'Étagère A-5',
    },

    # === FREINAGE ===
    {
        'nom': 'Plaquettes de frein Brembo P85020',
        'ref': 'P85020',
        'description': 'Plaquettes de frein avant premium. Compatible Renault Megane 3, Fluence, Scenic 3. Excellente performance de freinage, faible bruit, longue durée de vie. Certification ECE R90.',
        'etat': 'Comme neuf',
        'categorie': 'Freinage',
        'sous_categorie': 'Plaquettes, Brembo',
        'prix_neuf': 89.00,
        'prix_achat': 42.00,
        'prix_vente': 62.00,
        'quantite': 8,
        'public': True,
        'lieu': 'Étagère C-1',
    },
    {
        'nom': 'Disques de frein ATE ventilés 280mm',
        'ref': '24.0112-0154.1',
        'description': 'Disques de frein avant ventilés 280mm. Haute qualité allemande, traitement anti-corrosion. Kit de 2 disques. Compatible Peugeot 307, 308, Citroën C4. Freinage progressif et sûr.',
        'etat': 'Comme neuf',
        'categorie': 'Freinage',
        'sous_categorie': 'Disques, ATE',
        'prix_neuf': 145.00,
        'prix_achat': 68.00,
        'prix_vente': 98.00,
        'quantite': 4,
        'public': True,
        'lieu': 'Étagère C-2',
    },
    {
        'nom': 'Étriers de frein TRW arrière',
        'ref': 'BHN935E',
        'description': 'Étrier de frein arrière gauche. Compatible Renault Clio 2, Kangoo. Piston en acier inoxydable Ø38mm, joint neuf inclus. Installation simple.',
        'etat': 'Bon état',
        'categorie': 'Freinage',
        'sous_categorie': 'Étrier, TRW',
        'prix_neuf': 95.00,
        'prix_achat': 42.00,
        'prix_vente': 65.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Étagère C-3',
    },
    {
        'nom': 'Maître-cylindre de frein ATE',
        'ref': '03.2120-4307.3',
        'description': 'Maître-cylindre de frein. Compatible Peugeot 206, 207. Double circuit, piston Ø19.05mm. Inclut bouchon et capteur de niveau intégré.',
        'etat': 'Très bon état',
        'categorie': 'Freinage',
        'sous_categorie': 'Maître-cylindre, ATE',
        'prix_neuf': 78.00,
        'prix_achat': 38.00,
        'prix_vente': 58.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Étagère C-4',
    },

    # === FILTRATION ===
    {
        'nom': 'Filtre à huile Mann W712/75',
        'ref': 'W 712/75',
        'description': 'Filtre à huile haute performance. Compatible essence et diesel: Renault, Peugeot, Citroën. Média filtrant multicouche, rétention 98%. Clapet anti-retour intégré.',
        'etat': 'Comme neuf',
        'categorie': 'Filtration',
        'sous_categorie': 'Filtre à huile, Mann',
        'prix_neuf': 12.50,
        'prix_achat': 5.80,
        'prix_vente': 8.90,
        'quantite': 25,
        'public': True,
        'lieu': 'Étagère D-1',
    },
    {
        'nom': 'Filtre à air Bosch F026400529',
        'ref': 'F026400529',
        'description': 'Filtre à air pour moteur essence. Compatible Renault Clio 3, Megane 2 1.4-1.6 16V. Améliore les performances, réduit la consommation. Papier plissé haute densité.',
        'etat': 'Comme neuf',
        'categorie': 'Filtration',
        'sous_categorie': 'Filtre à air, Bosch',
        'prix_neuf': 18.00,
        'prix_achat': 8.50,
        'prix_vente': 13.50,
        'quantite': 15,
        'public': True,
        'lieu': 'Étagère D-1',
    },
    {
        'nom': 'Filtre à carburant Mahle KL440',
        'ref': 'KL 440',
        'description': 'Filtre à carburant diesel. Compatible Renault 1.5 dCi, Nissan 1.5 dCi. Rétention eau et particules. Cartouche avec joints inclus. Empêche la corrosion.',
        'etat': 'Comme neuf',
        'categorie': 'Filtration',
        'sous_categorie': 'Filtre carburant, Mahle',
        'prix_neuf': 22.00,
        'prix_achat': 11.00,
        'prix_vente': 16.50,
        'quantite': 10,
        'public': True,
        'lieu': 'Étagère D-1',
    },
    {
        'nom': 'Filtre habitacle charbon actif',
        'ref': 'MANN CUK2440',
        'description': 'Filtre d\'habitacle au charbon actif. Anti-allergène, anti-pollens, anti-odeurs. Compatible Peugeot 206, 307, Citroën C3, C4. Installation facile.',
        'etat': 'Comme neuf',
        'categorie': 'Filtration',
        'sous_categorie': 'Filtre habitacle, Mann',
        'prix_neuf': 16.00,
        'prix_achat': 7.50,
        'prix_vente': 12.00,
        'quantite': 12,
        'public': True,
        'lieu': 'Étagère D-2',
    },

    # === REFROIDISSEMENT ===
    {
        'nom': 'Pompe à eau Gates WP0045',
        'ref': 'WP0045',
        'description': 'Pompe à eau + joint. Compatible Renault 1.5 dCi K9K. Débit optimal 120L/min. Palier renforcé, étanchéité garantie. Installation avec kit distribution recommandée.',
        'etat': 'Comme neuf',
        'categorie': 'Refroidissement',
        'sous_categorie': 'Pompe à eau, Gates',
        'prix_neuf': 85.00,
        'prix_achat': 42.00,
        'prix_vente': 62.00,
        'quantite': 3,
        'public': True,
        'lieu': 'Étagère E-1',
    },
    {
        'nom': 'Radiateur Nissens 63002A',
        'ref': '63002A',
        'description': 'Radiateur de refroidissement moteur. Aluminium haute qualité, soudure brasée. Pour Peugeot 206 1.4-1.6 essence. Dimensions: 415x378x23mm. Pression testée 2 bars.',
        'etat': 'Très bon état',
        'categorie': 'Refroidissement',
        'sous_categorie': 'Radiateur, Nissens',
        'prix_neuf': 195.00,
        'prix_achat': 85.00,
        'prix_vente': 135.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Zone radiateurs',
    },
    {
        'nom': 'Thermostat Wahler 3091.87D',
        'ref': '3091.87D',
        'description': 'Thermostat avec joint. Température d\'ouverture 87°C. Compatible Renault Clio, Megane, Scenic 1.5-1.9 dCi. Régulation précise température moteur.',
        'etat': 'Comme neuf',
        'categorie': 'Refroidissement',
        'sous_categorie': 'Thermostat, Wahler',
        'prix_neuf': 28.00,
        'prix_achat': 14.00,
        'prix_vente': 21.00,
        'quantite': 8,
        'public': True,
        'lieu': 'Étagère E-2',
    },
    {
        'nom': 'Vase d\'expansion Vaico V46-0548',
        'ref': 'V46-0548',
        'description': 'Vase d\'expansion liquide de refroidissement avec bouchon. Compatible Renault Megane 2, Scenic 2. Capacité 1.5L, plastique haute résistance thermique.',
        'etat': 'Comme neuf',
        'categorie': 'Refroidissement',
        'sous_categorie': 'Vase expansion, Vaico',
        'prix_neuf': 32.00,
        'prix_achat': 16.00,
        'prix_vente': 24.00,
        'quantite': 4,
        'public': True,
        'lieu': 'Étagère E-3',
    },

    # === TRANSMISSION ===
    {
        'nom': 'Kit Embrayage Valeo 826320',
        'ref': '826320',
        'description': 'Kit embrayage complet 3 pièces: disque Ø200mm, mécanisme, butée hydraulique. Pour Renault Clio 3 1.5 dCi 65-85cv. Couple 240Nm. Installation pro recommandée.',
        'etat': 'Comme neuf',
        'categorie': 'Transmission',
        'sous_categorie': 'Embrayage, Valeo',
        'prix_neuf': 265.00,
        'prix_achat': 135.00,
        'prix_vente': 195.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Étagère F-1',
    },
    {
        'nom': 'Cardan droit Lobro 304285',
        'ref': '304285',
        'description': 'Cardan de transmission droit. Compatible Peugeot 206, 307 1.4-1.6 essence. Longueur 620mm, soufflets neufs inclus, graisse haute performance. Équilibrage dynamique.',
        'etat': 'Très bon état',
        'categorie': 'Transmission',
        'sous_categorie': 'Cardan, Lobro',
        'prix_neuf': 145.00,
        'prix_achat': 68.00,
        'prix_vente': 98.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Étagère F-2',
    },
    {
        'nom': 'Soufflet de cardan SKF VKJP01002',
        'ref': 'VKJP01002',
        'description': 'Kit soufflet de cardan côté roue avec colliers. Compatible universel Ø65-100mm. Caoutchouc thermoplastique résistant graisse et température. Installation simple.',
        'etat': 'Comme neuf',
        'categorie': 'Transmission',
        'sous_categorie': 'Soufflet, SKF',
        'prix_neuf': 18.00,
        'prix_achat': 8.50,
        'prix_vente': 13.50,
        'quantite': 10,
        'public': True,
        'lieu': 'Étagère F-3',
    },

    # === SUSPENSION ===
    {
        'nom': 'Amortisseur Sachs 313527',
        'ref': '313527',
        'description': 'Amortisseur avant à gaz. Compatible Renault Megane 2, Scenic 2. Confort et tenue de route optimaux. Piston Ø33mm, course 172mm. Technologie gaz basse pression.',
        'etat': 'Très bon état',
        'categorie': 'Suspension',
        'sous_categorie': 'Amortisseur, Sachs',
        'prix_neuf': 95.00,
        'prix_achat': 48.00,
        'prix_vente': 68.00,
        'quantite': 6,
        'public': True,
        'lieu': 'Étagère G-1',
    },
    {
        'nom': 'Ressort de suspension Lesjöfors 4028327',
        'ref': '4028327',
        'description': 'Ressort hélicoïdal avant. Compatible Peugeot 307. Charge 750kg, hauteur libre 335mm. Acier spécial traité anticorrosion. Remplacement par paire recommandé.',
        'etat': 'Comme neuf',
        'categorie': 'Suspension',
        'sous_categorie': 'Ressort, Lesjöfors',
        'prix_neuf': 58.00,
        'prix_achat': 28.00,
        'prix_vente': 42.00,
        'quantite': 4,
        'public': True,
        'lieu': 'Étagère G-2',
    },
    {
        'nom': 'Silent-bloc de bras Lemförder 34870',
        'ref': '34870 01',
        'description': 'Silent-bloc de bras de suspension avant. Compatible Renault Megane 2, Scenic 2. Caoutchouc renforcé EPDM, bague métal. Réduit vibrations et bruit.',
        'etat': 'Comme neuf',
        'categorie': 'Suspension',
        'sous_categorie': 'Silent-bloc, Lemförder',
        'prix_neuf': 22.00,
        'prix_achat': 11.00,
        'prix_vente': 16.50,
        'quantite': 8,
        'public': True,
        'lieu': 'Étagère G-3',
    },

    # === DIRECTION ===
    {
        'nom': 'Rotule de direction TRW JTE1077',
        'ref': 'JTE1077',
        'description': 'Rotule de direction avant gauche/droite. Compatible Renault Clio 2, Kangoo. Qualité OE, filetage M12x1.25. Joint à rotule étanche, graisse longue durée.',
        'etat': 'Comme neuf',
        'categorie': 'Direction',
        'sous_categorie': 'Rotule, TRW',
        'prix_neuf': 42.00,
        'prix_achat': 19.00,
        'prix_vente': 28.00,
        'quantite': 8,
        'public': True,
        'lieu': 'Étagère H-1',
    },
    {
        'nom': 'Crémaillère de direction TRW',
        'ref': 'JRP1562',
        'description': 'Crémaillère de direction assistée hydraulique. Compatible Peugeot 206. Rapport 17:1, course 160mm. Révisée et testée, joints neufs.',
        'etat': 'Bon état',
        'categorie': 'Direction',
        'sous_categorie': 'Crémaillère, TRW',
        'prix_neuf': 285.00,
        'prix_achat': 125.00,
        'prix_vente': 185.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Zone pièces volumineuses',
    },
    {
        'nom': 'Biellette de direction Moog RE-DS-7296',
        'ref': 'RE-DS-7296',
        'description': 'Biellette de direction avant droite. Compatible Renault Megane 2, Scenic 2. Longueur 275mm, rotule sphérique auto-lubrifiante. Qualité premium.',
        'etat': 'Comme neuf',
        'categorie': 'Direction',
        'sous_categorie': 'Biellette, Moog',
        'prix_neuf': 38.00,
        'prix_achat': 18.00,
        'prix_vente': 27.00,
        'quantite': 6,
        'public': True,
        'lieu': 'Étagère H-2',
    },

    # === DISTRIBUTION ===
    {
        'nom': 'Kit courroie distribution Gates K015491XS',
        'ref': 'K015491XS',
        'description': 'Kit distribution complet: courroie renforcée 137 dents, 2 galets tendeurs, pompe à eau. Compatible Peugeot 307 1.6 HDi 110cv. Remplacement 80000-120000km.',
        'etat': 'Comme neuf',
        'categorie': 'Distribution',
        'sous_categorie': 'Courroie, Gates',
        'prix_neuf': 125.00,
        'prix_achat': 62.00,
        'prix_vente': 89.00,
        'quantite': 3,
        'public': True,
        'lieu': 'Étagère I-1',
    },
    {
        'nom': 'Courroie accessoires Continental 6PK1193',
        'ref': '6PK1193',
        'description': 'Courroie striée 6 nervures 1193mm. Compatible Renault, Peugeot, Citroën diesel. EPDM haute résistance, low-stretch technology. Durée de vie 60000km.',
        'etat': 'Comme neuf',
        'categorie': 'Distribution',
        'sous_categorie': 'Courroie accessoires, Continental',
        'prix_neuf': 24.00,
        'prix_achat': 12.00,
        'prix_vente': 18.00,
        'quantite': 10,
        'public': True,
        'lieu': 'Étagère I-2',
    },

    # === ÉCHAPPEMENT ===
    {
        'nom': 'Silencieux arrière Walker 16862',
        'ref': '16862',
        'description': 'Silencieux arrière en acier aluminisé. Compatible Renault Clio 2 1.2-1.4 essence. Sortie ronde Ø50mm, longueur 950mm. Anti-corrosion, homologué CE.',
        'etat': 'Bon état',
        'categorie': 'Échappement',
        'sous_categorie': 'Silencieux, Walker',
        'prix_neuf': 165.00,
        'prix_achat': 72.00,
        'prix_vente': 115.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Zone échappements',
    },
    {
        'nom': 'Catalyseur Walker 20501',
        'ref': '20501',
        'description': 'Catalyseur échappement norme Euro 4. Compatible Renault Clio 2 1.4 essence. Céramique avec métaux précieux, réduit CO, HC, NOx. Homologué contrôle technique.',
        'etat': 'Très bon état',
        'categorie': 'Échappement',
        'sous_categorie': 'Catalyseur, Walker',
        'prix_neuf': 385.00,
        'prix_achat': 165.00,
        'prix_vente': 245.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Zone échappements',
    },
    {
        'nom': 'Sonde lambda Bosch 0258017025',
        'ref': '0258017025',
        'description': 'Sonde lambda / capteur oxygène avant catalyseur. Compatible Peugeot, Citroën, Renault essence. 4 fils, chauffage intégré. Temps de réponse <300ms.',
        'etat': 'Comme neuf',
        'categorie': 'Échappement',
        'sous_categorie': 'Sonde lambda, Bosch',
        'prix_neuf': 95.00,
        'prix_achat': 45.00,
        'prix_vente': 68.00,
        'quantite': 3,
        'public': True,
        'lieu': 'Étagère J-1',
    },

    # === TURBO / ADMISSION ===
    {
        'nom': 'Turbocompresseur Garrett reconditionné',
        'ref': '753420-5006S',
        'description': 'Turbocompresseur reconditionné et équilibré. Compatible Renault 1.5 dCi 105cv K9K. Pression boost 1.4 bar. Garantie 12 mois. CHRA neuf, paliers neufs.',
        'etat': 'Bon état',
        'categorie': 'Admission',
        'sous_categorie': 'Turbo, Garrett',
        'prix_neuf': 850.00,
        'prix_achat': 320.00,
        'prix_vente': 495.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Vitrine sécurisée',
    },
    {
        'nom': 'Vanne EGR Pierburg 7.24809.20.0',
        'ref': '7.24809.20.0',
        'description': 'Vanne EGR électrique. Compatible Renault 1.5 dCi, 1.9 dCi. Réduit émissions NOx, améliore combustion. Moteur pas-à-pas intégré, position variable.',
        'etat': 'Très bon état',
        'categorie': 'Admission',
        'sous_categorie': 'Vanne EGR, Pierburg',
        'prix_neuf': 125.00,
        'prix_achat': 58.00,
        'prix_vente': 85.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Étagère K-1',
    },
    {
        'nom': 'Débitmètre d\'air Bosch 0281002461',
        'ref': '0281002461',
        'description': 'Débitmètre / capteur de masse d\'air. Compatible Renault 1.5 dCi, 1.9 dCi. Film chaud, mesure précise 2-400kg/h. Capteur température intégré.',
        'etat': 'Comme neuf',
        'categorie': 'Admission',
        'sous_categorie': 'Débitmètre, Bosch',
        'prix_neuf': 145.00,
        'prix_achat': 68.00,
        'prix_vente': 98.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Étagère K-2',
    },

    # === CLIMATISATION ===
    {
        'nom': 'Compresseur clim Denso DCP17045',
        'ref': 'DCP17045',
        'description': 'Compresseur de climatisation neuf avec huile PAG. Compatible Peugeot 308. Gaz R134a, cylindrée 170cc, poulie 6 cannelures. Garantie 24 mois.',
        'etat': 'Comme neuf',
        'categorie': 'Climatisation',
        'sous_categorie': 'Compresseur, Denso',
        'prix_neuf': 425.00,
        'prix_achat': 195.00,
        'prix_vente': 295.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Étagère L-1',
    },
    {
        'nom': 'Condenseur climatisation Valeo 817807',
        'ref': '817807',
        'description': 'Condenseur de climatisation avec filtre déshydrateur. Compatible Renault Megane 2. Aluminium, dimensions 600x380x16mm. Refroidissement optimal.',
        'etat': 'Très bon état',
        'categorie': 'Climatisation',
        'sous_categorie': 'Condenseur, Valeo',
        'prix_neuf': 145.00,
        'prix_achat': 68.00,
        'prix_vente': 98.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Zone radiateurs',
    },

    # === CARROSSERIE ===
    {
        'nom': 'Rétroviseur droit électrique Peugeot 206',
        'ref': '8149.E5',
        'description': 'Rétroviseur extérieur droit électrique. Rabattable manuel, chauffant, 5 broches. Couleur noir texturé, coque + glace. Compatible phase 1 et 2.',
        'etat': 'Très bon état',
        'categorie': 'Carrosserie',
        'sous_categorie': 'Rétroviseur, Peugeot',
        'prix_neuf': 145.00,
        'prix_achat': 55.00,
        'prix_vente': 89.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Étagère M-1',
    },
    {
        'nom': 'Pare-chocs avant Renault Clio 3',
        'ref': '7701208225',
        'description': 'Pare-chocs avant pour Clio 3 phase 2. Noir texturé, apprêté, prêt à peindre. Avec emplacements antibrouillards. Plastique ABS haute résistance chocs.',
        'etat': 'Bon état',
        'categorie': 'Carrosserie',
        'sous_categorie': 'Pare-chocs, Renault',
        'prix_neuf': 185.00,
        'prix_achat': 78.00,
        'prix_vente': 125.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Zone pièces volumineuses',
    },

    # === ÉCLAIRAGE ===
    {
        'nom': 'Projecteur avant Hella 1EG247038011',
        'ref': '1EG 247 038-011',
        'description': 'Phare avant droit H7+H1. Compatible Renault Megane 2 phase 1. Réglage électrique, fond noir. Optique claire européenne, homologué CE.',
        'etat': 'Bon état',
        'categorie': 'Éclairage',
        'sous_categorie': 'Phare, Hella',
        'prix_neuf': 185.00,
        'prix_achat': 78.00,
        'prix_vente': 125.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Étagère N-1',
    },
    {
        'nom': 'Feu arrière LED Valeo 043660',
        'ref': '043660',
        'description': 'Feu arrière gauche LED. Compatible Peugeot 308. Fond rouge/blanc, technologie LED longue durée. Installation plug & play, étanche IP67.',
        'etat': 'Comme neuf',
        'categorie': 'Éclairage',
        'sous_categorie': 'Feu arrière, Valeo',
        'prix_neuf': 165.00,
        'prix_achat': 78.00,
        'prix_vente': 115.00,
        'quantite': 1,
        'public': True,
        'lieu': 'Étagère N-2',
    },
    {
        'nom': 'Kit ampoules Philips H7 +130%',
        'ref': 'H7 12972XV+S2',
        'description': 'Lot de 2 ampoules H7 12V 55W X-tremeVision +130% plus de lumière. Portée +45m, température 3700K. Homologuées route, durée de vie 450h.',
        'etat': 'Comme neuf',
        'categorie': 'Éclairage',
        'sous_categorie': 'Ampoules, Philips',
        'prix_neuf': 28.00,
        'prix_achat': 14.00,
        'prix_vente': 21.00,
        'quantite': 15,
        'public': True,
        'lieu': 'Étagère N-3',
    },

    # === ACCESSOIRES & CONSOMMABLES ===
    {
        'nom': 'Balai d\'essuie-glace Bosch Aerotwin 650mm',
        'ref': 'AR26U',
        'description': 'Balai essuie-glace avant plat. Longueur 650mm, technologie Aerotwin sans arceau. Caoutchouc naturel, adaptateur universel inclus.',
        'etat': 'Comme neuf',
        'categorie': 'Accessoires',
        'sous_categorie': 'Essuie-glace, Bosch',
        'prix_neuf': 18.00,
        'prix_achat': 9.00,
        'prix_vente': 13.50,
        'quantite': 20,
        'public': True,
        'lieu': 'Étagère O-1',
    },
    {
        'nom': 'Bougies d\'allumage NGK BKR6E',
        'ref': 'BKR6E (2288)',
        'description': 'Bougies d\'allumage essence. Électrode nickel, écartement 1.0mm. Compatible moteurs 1.4-1.6 essence Renault, Peugeot. Lot de 4 bougies.',
        'etat': 'Comme neuf',
        'categorie': 'Électricité',
        'sous_categorie': 'Bougies, NGK',
        'prix_neuf': 24.00,
        'prix_achat': 12.00,
        'prix_vente': 18.00,
        'quantite': 12,
        'public': True,
        'lieu': 'Étagère O-2',
    },
    {
        'nom': 'Joint de culasse Elring 026.870',
        'ref': '026.870',
        'description': 'Joint de culasse multicouche MLS. Compatible Renault 1.5 dCi K9K. Épaisseur 1.2mm, 3 couches acier. Résistance haute température et pression.',
        'etat': 'Comme neuf',
        'categorie': 'Moteur',
        'sous_categorie': 'Joint culasse, Elring',
        'prix_neuf': 78.00,
        'prix_achat': 38.00,
        'prix_vente': 58.00,
        'quantite': 2,
        'public': True,
        'lieu': 'Étagère P-1',
    },
]

# 🛢️ INVENTAIRE LIQUIDES & LUBRIFIANTS 🛢️
LIQUIDES_DATA = [
    {
        'nom': 'Huile Moteur Castrol Edge 5W30 C3',
        'ref': '15669E',
        'description': 'Huile moteur 100% synthétique nouvelle génération. Protection maximale du moteur, technologie Fluid Titanium. Réduit friction et usure. Idéale vidanges longlife.',
        'categorie': 'Huiles',
        'sous_categorie': 'Huile moteur, Castrol',
        'marque': 'Castrol',
        'litres': 45.0,
        'quantite_min': 20.0,
        'usage_hebdo': 8.0,
        'viscosite': '5W30',
        'norme': 'ACEA C3, API SN, VW 504.00/507.00, BMW LL-04',
        'usage': 'Moteurs essence et diesel récents avec FAP/DPF',
        'prix_achat': 6.50,
        'prix_vente': 11.90,
        'public': True,
    },
    {
        'nom': 'Huile Moteur Total Quartz 9000 5W40',
        'ref': '183199',
        'description': 'Huile moteur synthétique haute performance. Protection longue durée, excellente stabilité thermique. Résiste aux sollicitations extrêmes. Recommandée constructeurs.',
        'categorie': 'Huiles',
        'sous_categorie': 'Huile moteur, Total',
        'marque': 'Total',
        'litres': 35.0,
        'quantite_min': 15.0,
        'usage_hebdo': 6.0,
        'viscosite': '5W40',
        'norme': 'ACEA A3/B4, API SN/CF, Renault RN0700/RN0710, PSA B71 2296',
        'usage': 'Moteurs essence et diesel toutes marques',
        'prix_achat': 7.20,
        'prix_vente': 12.90,
        'public': True,
    },
    {
        'nom': 'Huile Moteur Mobil 1 ESP 0W30',
        'ref': '153668',
        'description': 'Huile moteur full synthétique low-SAPS. Protège filtres à particules et catalyseurs. Démarrage à froid facilité. Économies carburant jusqu\'à 2%.',
        'categorie': 'Huiles',
        'sous_categorie': 'Huile moteur, Mobil',
        'marque': 'Mobil 1',
        'litres': 28.0,
        'quantite_min': 12.0,
        'usage_hebdo': 4.0,
        'viscosite': '0W30',
        'norme': 'ACEA C2/C3, API SN, Mercedes MB 229.52, Porsche C30',
        'usage': 'Moteurs essence et diesel Euro 5/6 avec FAP',
        'prix_achat': 8.90,
        'prix_vente': 15.90,
        'public': True,
    },
    {
        'nom': 'Huile Diesel ELF Evolution 700 Turbo Diesel 10W40',
        'ref': '194839',
        'description': 'Huile moteur semi-synthétique spéciale diesel. Excellente résistance oxydation et encrassement. Protection turbo et injecteurs. Rapport qualité/prix optimal.',
        'categorie': 'Huiles',
        'sous_categorie': 'Huile moteur, ELF',
        'marque': 'ELF',
        'litres': 52.0,
        'quantite_min': 25.0,
        'usage_hebdo': 10.0,
        'viscosite': '10W40',
        'norme': 'ACEA A3/B4, API SN/CF, Renault RN0700, PSA B71 2294',
        'usage': 'Moteurs diesel et essence avec ou sans turbo',
        'prix_achat': 4.80,
        'prix_vente': 8.90,
        'public': True,
    },
    {
        'nom': 'Huile Boîte de Vitesse Motul Gear 300 75W90',
        'ref': '105777',
        'description': 'Huile de boîte de vitesse 100% synthétique. Protection extrême des engrenages, synchroniseurs et roulements. Excellent comportement températures basses et hautes.',
        'categorie': 'Huiles',
        'sous_categorie': 'Huile boîte, Motul',
        'marque': 'Motul',
        'litres': 12.0,
        'quantite_min': 5.0,
        'usage_hebdo': 1.5,
        'viscosite': '75W90',
        'norme': 'API GL-5, MIL-L-2105D, PSA B71 2330',
        'usage': 'Boîtes de vitesses manuelles haute performance',
        'prix_achat': 12.50,
        'prix_vente': 19.90,
        'public': True,
    },
    {
        'nom': 'Huile Boîte Auto Total Fluide XLD FE 75W',
        'ref': '213930',
        'description': 'Fluide pour boîtes automatiques et robotisées. Compatible EDC, DSG, Powershift. Excellente stabilité friction, protection embrayages. Longue durée de vie.',
        'categorie': 'Huiles',
        'sous_categorie': 'Huile boîte auto, Total',
        'marque': 'Total',
        'litres': 8.0,
        'quantite_min': 3.0,
        'usage_hebdo': 0.8,
        'viscosite': '75W',
        'norme': 'PSA S71 2710, VW G 052 182, Ford WSS-M2C917-A',
        'usage': 'Boîtes automatiques et robotisées récentes',
        'prix_achat': 15.00,
        'prix_vente': 24.90,
        'public': True,
    },
    {
        'nom': 'Liquide de Refroidissement Total Glacelf Auto Supra',
        'ref': '213666',
        'description': 'Liquide de refroidissement antigel concentré -37°C. Protège contre gel, surchauffe, corrosion et cavitation. Compatible tous métaux et caoutchoucs. Biodégradable.',
        'categorie': 'Refroidissement',
        'sous_categorie': 'Liquide refroidissement, Total',
        'marque': 'Total',
        'litres': 60.0,
        'quantite_min': 25.0,
        'usage_hebdo': 3.0,
        'viscosite': 'N/A',
        'norme': 'AFNOR NF R15-601, ASTM D3306, SAE J1034',
        'usage': 'Tous véhicules essence et diesel, dilution 50%',
        'prix_achat': 4.20,
        'prix_vente': 7.50,
        'public': True,
    },
    {
        'nom': 'Liquide de Refroidissement Castrol Radicool NF',
        'ref': '15B1E4',
        'description': 'Antigel haute performance prêt à l\'emploi -26°C. Formule OAT sans silicates ni phosphates. Longlife 5 ans/250000km. Protection aluminium et fonte.',
        'categorie': 'Refroidissement',
        'sous_categorie': 'Liquide refroidissement, Castrol',
        'marque': 'Castrol',
        'litres': 35.0,
        'quantite_min': 15.0,
        'usage_hebdo': 2.0,
        'viscosite': 'N/A',
        'norme': 'AFNOR NF R15-601, BS 6580:2010',
        'usage': 'Tous circuits de refroidissement, prêt à l\'emploi',
        'prix_achat': 5.50,
        'prix_vente': 9.90,
        'public': True,
    },
    {
        'nom': 'Liquide de Frein DOT 4 ATE',
        'ref': '03990157032',
        'description': 'Liquide de frein synthétique DOT 4. Point d\'ébullition sec 265°C / humide 165°C. Excellente fluidité à froid -40°C. Compatible ABS, ESP, ASR.',
        'categorie': 'Freinage',
        'sous_categorie': 'Liquide frein, ATE',
        'marque': 'ATE',
        'litres': 8.0,
        'quantite_min': 3.0,
        'usage_hebdo': 0.5,
        'viscosite': 'N/A',
        'norme': 'DOT 4, FMVSS 116, ISO 4925, SAE J1703',
        'usage': 'Systèmes de freinage hydraulique tous véhicules',
        'prix_achat': 8.50,
        'prix_vente': 14.90,
        'public': True,
    },
    {
        'nom': 'Liquide de Frein DOT 5.1 Bosch',
        'ref': '1987479120',
        'description': 'Liquide de frein haute performance DOT 5.1. Point d\'ébullition sec 270°C. Idéal conduite sportive et sollicitations intenses. Non hygroscopique optimisé.',
        'categorie': 'Freinage',
        'sous_categorie': 'Liquide frein, Bosch',
        'marque': 'Bosch',
        'litres': 5.0,
        'quantite_min': 2.0,
        'usage_hebdo': 0.3,
        'viscosite': 'N/A',
        'norme': 'DOT 5.1, FMVSS 116, ISO 4925',
        'usage': 'Freinage haute performance, sport, montagne',
        'prix_achat': 12.00,
        'prix_vente': 19.90,
        'public': True,
    },
    {
        'nom': 'Huile Hydraulique LHM+ Citroën',
        'ref': '1610 05',
        'description': 'Fluide hydraulique minéral vert LHM+. Pour suspensions hydropneumatiques, direction et freins Citroën. Spécifications strictes constructeur. Viscosité stable.',
        'categorie': 'Hydraulique',
        'sous_categorie': 'Liquide hydraulique, Citroën',
        'marque': 'Citroën',
        'litres': 15.0,
        'quantite_min': 5.0,
        'usage_hebdo': 1.0,
        'viscosite': 'ISO 11',
        'norme': 'LHM+, PSA S71 2710',
        'usage': 'Suspensions hydrauliques Citroën (C5, C6, Xantia...)',
        'prix_achat': 15.00,
        'prix_vente': 24.90,
        'public': True,
    },
    {
        'nom': 'Liquide de Direction Assistée Febi 06161',
        'ref': '06161',
        'description': 'Fluide pour direction assistée hydraulique. Protège contre usure, corrosion et fuites. Additifs anti-mousse. Compatible pompes, crémaillères et flexibles.',
        'categorie': 'Direction',
        'sous_categorie': 'Liquide direction, Febi',
        'marque': 'Febi',
        'litres': 18.0,
        'quantite_min': 8.0,
        'usage_hebdo': 1.2,
        'viscosite': 'ISO 46',
        'norme': 'DIN 51524 T3, Dexron IID, MB 236.3',
        'usage': 'Directions assistées hydrauliques tous constructeurs',
        'prix_achat': 5.50,
        'prix_vente': 9.90,
        'public': True,
    },
    {
        'nom': 'Liquide de Direction ZF LifeguardFluid 6',
        'ref': 'S671090170',
        'description': 'Fluide synthétique pour directions assistées électro-hydrauliques. Longue durée de vie, excellente protection. Compatible Mercedes, BMW, Audi.',
        'categorie': 'Direction',
        'sous_categorie': 'Liquide direction, ZF',
        'marque': 'ZF',
        'litres': 6.0,
        'quantite_min': 2.0,
        'usage_hebdo': 0.4,
        'viscosite': 'N/A',
        'norme': 'MB 236.17, BMW 83290429576',
        'usage': 'Directions assistées électro-hydrauliques haut de gamme',
        'prix_achat': 18.00,
        'prix_vente': 29.90,
        'public': True,
    },
    {
        'nom': 'Lave-Glace Concentré -25°C',
        'ref': 'LAVGLA-5L',
        'description': 'Lave-glace concentré 4 saisons. Dilution 1:10. Senteur agrumes fraîche. Anti-gel -25°C, nettoie insectes, pollens, traces graisseuses. Sans méthanol.',
        'categorie': 'Entretien',
        'sous_categorie': 'Lave-glace, Entretien',
        'marque': 'Autosmart',
        'litres': 25.0,
        'quantite_min': 10.0,
        'usage_hebdo': 4.0,
        'viscosite': 'N/A',
        'norme': 'N/A',
        'usage': 'Système lave-glace toutes saisons',
        'prix_achat': 2.80,
        'prix_vente': 5.50,
        'public': True,
    },
    {
        'nom': 'Lave-Glace Été Concentré 1:100',
        'ref': 'LAVETE-2L',
        'description': 'Lave-glace été super concentré 1:100. Senteur citron. Nettoie parfaitement insectes écrasés, pollen, poussières. Ne laisse pas de traces. Économique.',
        'categorie': 'Entretien',
        'sous_categorie': 'Lave-glace, Entretien',
        'marque': 'Sonax',
        'litres': 18.0,
        'quantite_min': 8.0,
        'usage_hebdo': 2.5,
        'viscosite': 'N/A',
        'norme': 'N/A',
        'usage': 'Système lave-glace période chaude',
        'prix_achat': 1.90,
        'prix_vente': 3.90,
        'public': True,
    },
    {
        'nom': 'AdBlue / AUS 32',
        'ref': 'ADBLUE-10L',
        'description': 'Solution d\'urée AUS 32 pour systèmes SCR diesel Euro 5/6. Réduit émissions NOx jusqu\'à 90%. Pureté 32.5%, conforme ISO 22241. Bidon 10L avec bec verseur.',
        'categorie': 'Carburant',
        'sous_categorie': 'AdBlue, SCR',
        'marque': 'Total',
        'litres': 80.0,
        'quantite_min': 30.0,
        'usage_hebdo': 6.0,
        'viscosite': 'N/A',
        'norme': 'ISO 22241, DIN 70070',
        'usage': 'Systèmes SCR moteurs diesel Euro 5 et 6',
        'prix_achat': 0.80,
        'prix_vente': 1.50,
        'public': True,
    },
    {
        'nom': 'Graisse Lithium Multi-usage',
        'ref': 'GRLI-500G',
        'description': 'Graisse au lithium universelle NLGI 2. Température -20°C à +120°C. Excellente adhérence, résiste eau et oxydation. Idéale roulements, articulations, câbles.',
        'categorie': 'Lubrifiants',
        'sous_categorie': 'Graisse, Cartouche',
        'marque': 'Mobil',
        'litres': 4.5,
        'quantite_min': 2.0,
        'usage_hebdo': 0.5,
        'viscosite': 'NLGI 2',
        'norme': 'DIN 51825',
        'usage': 'Lubrification générale chassis, roulements, suspensions',
        'prix_achat': 8.00,
        'prix_vente': 14.50,
        'public': True,
    },
    {
        'nom': 'Spray Lubrifiant WD-40 Multifonction',
        'ref': 'WD40-400ML',
        'description': 'Aérosol multifonction 400ml. Dégrippant, lubrifiant, protecteur, nettoyant, anti-humidité. Formule pénétrante. Indispensable en atelier.',
        'categorie': 'Lubrifiants',
        'sous_categorie': 'Spray, WD-40',
        'marque': 'WD-40',
        'litres': 9.6,
        'quantite_min': 5.0,
        'usage_hebdo': 1.2,
        'viscosite': 'N/A',
        'norme': 'N/A',
        'usage': 'Dégrippant et lubrifiant universel atelier',
        'prix_achat': 4.50,
        'prix_vente': 7.90,
        'public': True,
    },
]

async def seed_database():
    print("🚀 Démarrage du peuplement ULTRA RÉALISTE de la base de données...")
    print("📦 Inventaire complet de garage automobile\n")
    
    # Vérifier si des articles existent déjà
    existing_count = await db.articles.count_documents({})
    if existing_count > 0:
        confirm = input(f"⚠️  Il y a déjà {existing_count} articles dans la base. Continuer quand même ? (y/N): ")
        if confirm.lower() != 'y':
            print("❌ Annulé.")
            return
    
    # Get next ID
    last_article = await db.articles.find_one({}, {'_id': 0, 'id': 1}, sort=[('id', -1)])
    next_id = (last_article['id'] + 1) if last_article else 1
    
    total_added = 0
    lieux_possibles = [
        'Étagère A-1', 'Étagère A-2', 'Étagère A-3', 'Étagère A-4', 'Étagère A-5',
        'Étagère B-1', 'Étagère B-2', 'Étagère B-3',
        'Étagère C-1', 'Étagère C-2', 'Étagère C-3',
        'Zone principale', 'Arrière-boutique', 'Zone batterie', 
        'Zone radiateurs', 'Zone échappements', 'Vitrine sécurisée',
        'Zone pièces volumineuses'
    ]
    
    # Ajouter les pièces
    print("🔧 Ajout des pièces détachées...")
    for piece in PIECES_DATA:
        sku = generate_sku()
        while await db.articles.find_one({'sku': sku}):
            sku = generate_sku()
        
        article_data = {
            'id': next_id,
            'type': 'piece',
            'sku': sku,
            'photos': get_image_for_article(piece['nom']),
            'posted_by': 'AdminLudo',
            'date_post': (datetime.now(timezone.utc) - timedelta(days=random.randint(1, 30))).isoformat(),
            'lieu': piece.get('lieu', random.choice(lieux_possibles)),
            **{k: v for k, v in piece.items() if k != 'lieu'}
        }
        
        await db.articles.insert_one(article_data)
        print(f"  ✅ {piece['nom']} - {piece['ref']} (#{next_id})")
        next_id += 1
        total_added += 1
    
    # Ajouter les liquides
    print("\n🛢️  Ajout des huiles et liquides...")
    for liquide in LIQUIDES_DATA:
        sku = generate_sku()
        while await db.articles.find_one({'sku': sku}):
            sku = generate_sku()
        
        article_data = {
            'id': next_id,
            'type': 'liquide',
            'sku': sku,
            'photos': get_image_for_article(liquide['nom']),
            'posted_by': 'AdminLudo',
            'date_post': (datetime.now(timezone.utc) - timedelta(days=random.randint(1, 20))).isoformat(),
            'quantite': 1,
            'public': True,
            **liquide
        }
        
        await db.articles.insert_one(article_data)
        print(f"  ✅ {liquide['nom']} - {liquide['ref']} ({liquide['litres']}L) (#{next_id})")
        next_id += 1
        total_added += 1
    
    print(f"\n🎉 Terminé ! {total_added} articles ajoutés avec succès !")
    print(f"\n📊 Résumé détaillé :")
    print(f"   - Pièces détachées : {len(PIECES_DATA)}")
    print(f"   - Huiles & Liquides : {len(LIQUIDES_DATA)}")
    print(f"   - Total articles : {total_added}")
    print(f"\n✨ Ton inventaire de DÉMO ULTRA RÉALISTE est prêt !")
    print(f"🚗 Toutes les pièces ont de vraies références constructeur")
    print(f"🔧 Catégories : Électricité, Freinage, Filtration, Refroidissement,")
    print(f"    Transmission, Suspension, Direction, Distribution, Échappement,")
    print(f"    Turbo/Admission, Climatisation, Carrosserie, Éclairage, Accessoires")
    print(f"🛢️  Liquides : Huiles moteur, boîte, refroidissement, frein, direction,")
    print(f"    lave-glace, AdBlue, graisses, sprays")

if __name__ == '__main__':
    try:
        asyncio.run(seed_database())
    except KeyboardInterrupt:
        print("\n❌ Annulé par l'utilisateur")
    except Exception as e:
        print(f"\n❌ Erreur: {e}")
        import traceback
        traceback.print_exc()
    finally:
        client.close()
